version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "6033:3306"
  ###< doctrine/doctrine-bundle ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]